-- SUPERSEDED — intentionally a no-op. Do not restore.
--
-- This migration was drafted against an assumed schema and never applied to any
-- database. It modelled `scores` as one row per dimension and `extracted_fields`
-- as pure provenance (no value), both of which contradict the live schema and
-- the extraction pipeline's contract.
--
-- The canonical shapes are:
--   * scores            — one row per deal, a named column per rubric dimension
--   * extracted_fields  — (deal_id, field_name, value, source, confidence)
--   * deals.round / deals.traction — jsonb, written verbatim from the extraction JSON
--
-- See 0004_pipeline_contract.sql, which reconciles the database with that contract.
-- Keeping this file as an empty placeholder preserves migration numbering.
